<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CHALAMA" ignored="0" name="Test" tests="9" failures="2" timestamp="2020-12-02T14:56:23 IST" time="43.93" errors="0">
  <testcase name="@AfterMethod tearDown" time="1.733" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:149)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.002" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:149)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.001" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:149)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.001" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:149)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.001" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:149)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.001" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:149)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.001" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:149)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.001" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:149)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="1.34" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:149)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="LoginWithBlank" time="0.106" classname="com.qa.TestCases.ManualLoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.TestCases.ManualLoginTest.LoginWithBlank(ManualLoginTest.java:12)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- LoginWithBlank -->
  <testcase name="LoginWithInvalidData" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithInvalidData -->
  <testcase name="LoginWithInvalidData" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithInvalidData -->
  <testcase name="LoginWithInvalidData" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithInvalidData -->
  <testcase name="LoginWithInvalidData" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithInvalidData -->
  <testcase name="LoginWithInvalidData" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithInvalidData -->
  <testcase name="LoginWithInvalidData" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithInvalidData -->
  <testcase name="LoginWithValidData" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithValidData -->
  <testcase name="SignupDetails" time="0.004" classname="signup.SignupTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at signup.SignupTest.SignupDetails(SignupTest.java:11)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- SignupDetails -->
</testsuite> <!-- Test -->
